apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-push-express-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: build-push-express
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce 
        resources:
          requests:
            storage: 1Gi
